version: '3'
services:
  models_api:
    image: models_api
    build: ./models_api
    container_name: models_api_container
    ports: 
      - "8501:8501"
  api:
    image: api
    build: ./api
    container_name: api
    ports: 
      - "5002:5000"
  webpage:
    image: app
    build: ./app
    container_name: app
    env_file:
      - app/.env
    ports:
      - "5003:5000"
  
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  db:
    image: mysql:5.7
    container_name: "mysql_container"
    volumes:
      - ./data/db:/var/lib/db  # mapping outside and inside
    ports:
      - 3306:3306  # outside (random) port : inside port from the image
    hostname: 
      - 'emergencyroom.ci8zphg60wmc.us-east-2.rds.amazonaws.com'
    environment:  
      MYSQL_ROOT_PASSWORD: "emr00mtr3nt036"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "emr00mtr3nt036"  # better use a different pwd from root