version: '3'
services:
  models_api:
    image: models_api
    build: ./models_api
    container_name: models_api
    restart: on-failure
    ports: 
      - "8501:8501"
  api:
    image: api
    build: ./api
    container_name: api
    restart: on-failure
    ports: 
      - "5002:5000"
    depends_on: 
      - models_api
  redis:
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
  app:
    image: app
    build: ./app
    container_name: app
    restart: on-failure
    env_file:
      - app/.env
    ports:
      - "5003:5000"
    depends_on: 
      - api
      - redis
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
  
